In [19]:
# Quietly load the files
.output <- source("./Functions/lecospectR.R", echo = FALSE, verbose = FALSE)

In [20]:
get_filename <- function(
    bandwidth, 
    count, 
    is_train = TRUE, 
    base_path = "Data/v2/") {
    if (is_train) {
        train_test_string <- "train"
    } else {
        train_test_string <- "test"
    }

    return(
        paste0(
            base_path,
            train_test_string,
            "_",
            bandwidth,
            "nm_",
            count,
            ".csv"
        )
    )
}

In [21]:
seeds <- c(
    #6265,
    #4041,
    #3621,
    #942,
    #3143,
    #1764,
    #1378,
    #3964,
    4270,
    5542,
    1816,
    2833,
    4024,
    3031,
    6389,
    1368,
    4900,
    4075,
    6232,
    7118,
    7590,
    7928,
    2725,
    2422,
    7475,
    3857,
    1652,
    2041,
    9017,
    6447
)

In [22]:
data_raw <- read.csv(file = "Data/Ground_Validation/PFT_image_spectra/PFT_Image_SpectralLib_Clean.csv")

In [23]:
indices <- get_vegetation_indices(df = data_raw, ml_model = NULL)

In [24]:
bands <- resample_df(df = data_raw)
colnames(bands)

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

  [1] "X"            "UID"          "ScanNum"      "sample_name"  "PFT"
  [6] "FncGrp1"      "Site"         "X398"         "X399"         "X400"
 [11] "X401"         "X402"         "X403"         "X404"         "X405"
 [16] "X406"         "X407"         "X408"         "X409"         "X410"
 [21] "X411"         "X412"         "X413"         "X414"         "X415"
 [26] "X416"         "X417"         "X418"         "X419"         "X420"
 [31] "X421"         "X422"         "X423"         "X424"         "X425"
 [36] "X426"         "X427"         "X428"         "X429"         "X430"
 [41] "X431"         "X432"         "X433"         "X434"         "X435"
 [46] "X436"         "X437"         "X438"         "X439"         "X440"
 [51] "X441"         "X442"         "X443"         "X444"         "X445"
 [56] "X446"         "X447"         "X448"         "X449"         "X450"
 [61] "X451"         "X452"         "X453"         "X454"         "X455"
 [66] "X456"         "X457"         "X458"         "X459"         "X460"
 [71] "X461"         "X462"         "X463"         "X464"         "X465"
 [76] "X466"         "X467"         "X468"         "X469"         "X470"
 [81] "X471"         "X472"         "X473"         "X474"         "X475"
 [86] "X476"         "X477"         "X478"         "X479"         "X480"
 [91] "X481"         "X482"         "X483"         "X484"         "X485"
 [96] "X486"         "X487"         "X488"         "X489"         "X490"
[101] "X491"         "X492"         "X493"         "X494"         "X495"
[106] "X496"         "X497"         "X498"         "X499"         "X500"
[111] "X501"         "X502"         "X503"         "X504"         "X505"
[116] "X506"         "X507"         "X508"         "X509"         "X510"
[121] "X511"         "X512"         "X513"         "X514"         "X515"
[126] "X516"         "X517"         "X518"         "X519"         "X520"
[131] "X521"         "X522"         "X523"         "X524"         "X525"
[136] "X526"         "X527"         "X528"         "X529"         "X530"
[141] "X531"         "X532"         "X533"         "X534"         "X535"
[146] "X536"         "X537"         "X538"         "X539"         "X540"
[151] "X541"         "X542"         "X543"         "X544"         "X545"
[156] "X546"         "X547"         "X548"         "X549"         "X550"
[161] "X551"         "X552"         "X553"         "X554"         "X555"
[166] "X556"         "X557"         "X558"         "X559"         "X560"
[171] "X561"         "X562"         "X563"         "X564"         "X565"
[176] "X566"         "X567"         "X568"         "X569"         "X570"
[181] "X571"         "X572"         "X573"         "X574"         "X575"
[186] "X576"         "X577"         "X578"         "X579"         "X580"
[191] "X581"         "X582"         "X583"         "X584"         "X585"
[196] "X586"         "X587"         "X588"         "X589"         "X590"
[201] "X591"         "X592"         "X593"         "X594"         "X595"
[206] "X596"         "X597"         "X598"         "X599"         "X600"
[211] "X601"         "X602"         "X603"         "X604"         "X605"
[216] "X606"         "X607"         "X608"         "X609"         "X610"
[221] "X611"         "X612"         "X613"         "X614"         "X615"
[226] "X616"         "X617"         "X618"         "X619"         "X620"
[231] "X621"         "X622"         "X623"         "X624"         "X625"
[236] "X626"         "X627"         "X628"         "X629"         "X630"
[241] "X631"         "X632"         "X633"         "X634"         "X635"
[246] "X636"         "X637"         "X638"         "X639"         "X640"
[251] "X641"         "X642"         "X643"         "X644"         "X645"
[256] "X646"         "X647"         "X648"         "X649"         "X650"
[261] "X651"         "X652"         "X653"         "X654"         "X655"
[266] "X656"         "X657"         "X658"         "X659"         "X660"
[271] "X661"         "X662"         "X663"         "X664"         "X665"
[276] "X666"         "X667"         "X668"         "X669"         "X670"
[281] "X671"         "X672"         "X673"         "X674"         "X675"
[286] "X676"         "X677"         "X678"         "X679"         "X680"
[291] "X681"         "X682"         "X683"         "X684"         "X685"
[296] "X686"         "X687"         "X688"         "X689"         "X690"
[301] "X691"         "X692"         "X693"         "X694"         "X695"
[306] "X696"         "X697"         "X698"         "X699"         "X700"
[311] "X701"         "X702"         "X703"         "X704"         "X705"
[316] "X706"         "X707"         "X708"         "X709"         "X710"
[321] "X711"         "X712"         "X713"         "X714"         "X715"
[326] "X716"         "X717"         "X718"         "X719"         "X720"
[331] "X721"         "X722"         "X723"         "X724"         "X725"
[336] "X726"         "X727"         "X728"         "X729"         "X730"
[341] "X731"         "X732"         "X733"         "X734"         "X735"
[346] "X736"         "X737"         "X738"         "X739"         "X740"
[351] "X741"         "X742"         "X743"         "X744"         "X745"
[356] "X746"         "X747"         "X748"         "X749"         "X750"
[361] "X751"         "X752"         "X753"         "X754"         "X755"
[366] "X756"         "X757"         "X758"         "X759"         "X760"
[371] "X761"         "X762"         "X763"         "X764"         "X765"
[376] "X766"         "X767"         "X768"         "X769"         "X770"
[381] "X771"         "X772"         "X773"         "X774"         "X775"
[386] "X776"         "X777"         "X778"         "X779"         "X780"
[391] "X781"         "X782"         "X783"         "X784"         "X785"
[396] "X786"         "X787"         "X788"         "X789"         "X790"
[401] "X791"         "X792"         "X793"         "X794"         "X795"
[406] "X796"         "X797"         "X798"         "X799"         "X800"
[411] "X801"         "X802"         "X803"         "X804"         "X805"
[416] "X806"         "X807"         "X808"         "X809"         "X810"
[421] "X811"         "X812"         "X813"         "X814"         "X815"
[426] "X816"         "X817"         "X818"         "X819"         "X820"
[431] "X821"         "X822"         "X823"         "X824"         "X825"
[436] "X826"         "X827"         "X828"         "X829"         "X830"
[441] "X831"         "X832"         "X833"         "X834"         "X835"
[446] "X836"         "X837"         "X838"         "X839"         "X840"
[451] "X841"         "X842"         "X843"         "X844"         "X845"
[456] "X846"         "X847"         "X848"         "X849"         "X850"
[461] "X851"         "X852"         "X853"         "X854"         "X855"
[466] "X856"         "X857"         "X858"         "X859"         "X860"
[471] "X861"         "X862"         "X863"         "X864"         "X865"
[476] "X866"         "X867"         "X868"         "X869"         "X870"
[481] "X871"         "X872"         "X873"         "X874"         "X875"
[486] "X876"         "X877"         "X878"         "X879"         "X880"
[491] "X881"         "X882"         "X883"         "X884"         "X885"
[496] "X886"         "X887"         "X888"         "X889"         "X890"
[501] "X891"         "X892"         "X893"         "X894"         "X895"
[506] "X896"         "X897"         "X898"         "X899"         "X900"
[511] "X901"         "X902"         "X903"         "X904"         "X905"
[516] "X906"         "X907"         "X908"         "X909"         "X910"
[521] "X911"         "X912"         "X913"         "X914"         "X915"
[526] "X916"         "X917"         "X918"         "X919"         "X920"
[531] "X921"         "X922"         "X923"         "X924"         "X925"
[536] "X926"         "X927"         "X928"         "X929"         "X930"
[541] "X931"         "X932"         "X933"         "X934"         "X935"
[546] "X936"         "X937"         "X938"         "X939"         "X940"
[551] "X941"         "X942"         "X943"         "X944"         "X945"
[556] "X946"         "X947"         "X948"         "X949"         "X950"
[561] "X951"         "X952"         "X953"         "X954"         "X955"
[566] "X956"         "X957"         "X958"         "X959"         "X960"
[571] "X961"         "X962"         "X963"         "X964"         "X965"
[576] "X966"         "X967"         "X968"         "X969"         "X970"
[581] "X971"         "X972"         "X973"         "X974"         "X975"
[586] "X976"         "X977"         "X978"         "X979"         "X980"
[591] "X981"         "X982"         "X983"         "X984"         "X985"
[596] "X986"         "X987"         "X988"         "X989"         "X990"
[601] "X991"         "X992"         "X993"         "X994"         "X995"
[606] "X996"         "X997"         "X998"         "X999"         "X402.593_5nm"
[611] "X407.593_5nm" "X412.593_5nm" "X417.593_5nm" "X422.593_5nm" "X427.593_5nm"
[616] "X432.593_5nm" "X437.593_5nm" "X442.593_5nm" "X447.593_5nm" "X452.593_5nm"
[621] "X457.593_5nm" "X462.593_5nm" "X467.593_5nm" "X472.593_5nm" "X477.593_5nm"
[626] "X482.593_5nm" "X487.593_5nm" "X492.593_5nm" "X497.593_5nm" "X502.593_5nm"
[631] "X507.593_5nm" "X512.593_5nm" "X517.593_5nm" "X522.593_5nm" "X527.593_5nm"
[636] "X532.593_5nm" "X537.593_5nm" "X542.593_5nm" "X547.593_5nm" "X552.593_5nm"
[641] "X557.593_5nm" "X562.593_5nm" "X567.593_5nm" "X572.593_5nm" "X577.593_5nm"
[646] "X582.593_5nm" "X587.593_5nm" "X592.593_5nm" "X597.593_5nm" "X602.593_5nm"
[651] "X607.593_5nm" "X612.593_5nm" "X617.593_5nm" "X622.593_5nm" "X627.593_5nm"
[656] "X632.593_5nm" "X637.593_5nm" "X642.593_5nm" "X647.593_5nm" "X652.593_5nm"
[661] "X657.593_5nm" "X662.593_5nm" "X667.593_5nm" "X672.593_5nm" "X677.593_5nm"
[666] "X682.593_5nm" "X687.593_5nm" "X692.593_5nm" "X697.593_5nm" "X702.593_5nm"
[671] "X707.593_5nm" "X712.593_5nm" "X717.593_5nm" "X722.593_5nm" "X727.593_5nm"
[676] "X732.593_5nm" "X737.593_5nm" "X742.593_5nm" "X747.593_5nm" "X752.593_5nm"
[681] "X757.593_5nm" "X762.593_5nm" "X767.593_5nm" "X772.593_5nm" "X777.593_5nm"
[686] "X782.593_5nm" "X787.593_5nm" "X792.593_5nm" "X797.593_5nm" "X802.593_5nm"
[691] "X807.593_5nm" "X812.593_5nm" "X817.593_5nm" "X822.593_5nm" "X827.593_5nm"
[696] "X832.593_5nm" "X837.593_5nm" "X842.593_5nm" "X847.593_5nm" "X852.593_5nm"
[701] "X857.593_5nm" "X862.593_5nm" "X867.593_5nm" "X872.593_5nm" "X877.593_5nm"
[706] "X882.593_5nm" "X887.593_5nm" "X892.593_5nm" "X897.593_5nm" "X902.593_5nm"
[711] "X907.593_5nm" "X912.593_5nm" "X917.593_5nm" "X922.593_5nm" "X927.593_5nm"
[716] "X932.593_5nm" "X937.593_5nm" "X942.593_5nm" "X947.593_5nm" "X952.593_5nm"
[721] "X957.593_5nm" "X962.593_5nm" "X967.593_5nm" "X972.593_5nm" "X977.593_5nm"
[726] "X982.593_5nm" "X987.593_5nm" "X992.593_5nm"

In [25]:
num_cols_initial <- ncol(data_raw)
num_cols_bands <- ncol(bands)

In [26]:
df <- cbind(bands, indices)

In [27]:
colnames(df)

  [1] "X"            "UID"          "ScanNum"      "sample_name"  "PFT"
  [6] "FncGrp1"      "Site"         "X398"         "X399"         "X400"
 [11] "X401"         "X402"         "X403"         "X404"         "X405"
 [16] "X406"         "X407"         "X408"         "X409"         "X410"
 [21] "X411"         "X412"         "X413"         "X414"         "X415"
 [26] "X416"         "X417"         "X418"         "X419"         "X420"
 [31] "X421"         "X422"         "X423"         "X424"         "X425"
 [36] "X426"         "X427"         "X428"         "X429"         "X430"
 [41] "X431"         "X432"         "X433"         "X434"         "X435"
 [46] "X436"         "X437"         "X438"         "X439"         "X440"
 [51] "X441"         "X442"         "X443"         "X444"         "X445"
 [56] "X446"         "X447"         "X448"         "X449"         "X450"
 [61] "X451"         "X452"         "X453"         "X454"         "X455"
 [66] "X456"         "X457"         "X458"         "X459"         "X460"
 [71] "X461"         "X462"         "X463"         "X464"         "X465"
 [76] "X466"         "X467"         "X468"         "X469"         "X470"
 [81] "X471"         "X472"         "X473"         "X474"         "X475"
 [86] "X476"         "X477"         "X478"         "X479"         "X480"
 [91] "X481"         "X482"         "X483"         "X484"         "X485"
 [96] "X486"         "X487"         "X488"         "X489"         "X490"
[101] "X491"         "X492"         "X493"         "X494"         "X495"
[106] "X496"         "X497"         "X498"         "X499"         "X500"
[111] "X501"         "X502"         "X503"         "X504"         "X505"
[116] "X506"         "X507"         "X508"         "X509"         "X510"
[121] "X511"         "X512"         "X513"         "X514"         "X515"
[126] "X516"         "X517"         "X518"         "X519"         "X520"
[131] "X521"         "X522"         "X523"         "X524"         "X525"
[136] "X526"         "X527"         "X528"         "X529"         "X530"
[141] "X531"         "X532"         "X533"         "X534"         "X535"
[146] "X536"         "X537"         "X538"         "X539"         "X540"
[151] "X541"         "X542"         "X543"         "X544"         "X545"
[156] "X546"         "X547"         "X548"         "X549"         "X550"
[161] "X551"         "X552"         "X553"         "X554"         "X555"
[166] "X556"         "X557"         "X558"         "X559"         "X560"
[171] "X561"         "X562"         "X563"         "X564"         "X565"
[176] "X566"         "X567"         "X568"         "X569"         "X570"
[181] "X571"         "X572"         "X573"         "X574"         "X575"
[186] "X576"         "X577"         "X578"         "X579"         "X580"
[191] "X581"         "X582"         "X583"         "X584"         "X585"
[196] "X586"         "X587"         "X588"         "X589"         "X590"
[201] "X591"         "X592"         "X593"         "X594"         "X595"
[206] "X596"         "X597"         "X598"         "X599"         "X600"
[211] "X601"         "X602"         "X603"         "X604"         "X605"
[216] "X606"         "X607"         "X608"         "X609"         "X610"
[221] "X611"         "X612"         "X613"         "X614"         "X615"
[226] "X616"         "X617"         "X618"         "X619"         "X620"
[231] "X621"         "X622"         "X623"         "X624"         "X625"
[236] "X626"         "X627"         "X628"         "X629"         "X630"
[241] "X631"         "X632"         "X633"         "X634"         "X635"
[246] "X636"         "X637"         "X638"         "X639"         "X640"
[251] "X641"         "X642"         "X643"         "X644"         "X645"
[256] "X646"         "X647"         "X648"         "X649"         "X650"
[261] "X651"         "X652"         "X653"         "X654"         "X655"
[266] "X656"         "X657"         "X658"         "X659"         "X660"
[271] "X661"         "X662"         "X663"         "X664"         "X665"
[276] "X666"         "X667"         "X668"         "X669"         "X670"
[281] "X671"         "X672"         "X673"         "X674"         "X675"
[286] "X676"         "X677"         "X678"         "X679"         "X680"
[291] "X681"         "X682"         "X683"         "X684"         "X685"
[296] "X686"         "X687"         "X688"         "X689"         "X690"
[301] "X691"         "X692"         "X693"         "X694"         "X695"
[306] "X696"         "X697"         "X698"         "X699"         "X700"
[311] "X701"         "X702"         "X703"         "X704"         "X705"
[316] "X706"         "X707"         "X708"         "X709"         "X710"
[321] "X711"         "X712"         "X713"         "X714"         "X715"
[326] "X716"         "X717"         "X718"         "X719"         "X720"
[331] "X721"         "X722"         "X723"         "X724"         "X725"
[336] "X726"         "X727"         "X728"         "X729"         "X730"
[341] "X731"         "X732"         "X733"         "X734"         "X735"
[346] "X736"         "X737"         "X738"         "X739"         "X740"
[351] "X741"         "X742"         "X743"         "X744"         "X745"
[356] "X746"         "X747"         "X748"         "X749"         "X750"
[361] "X751"         "X752"         "X753"         "X754"         "X755"
[366] "X756"         "X757"         "X758"         "X759"         "X760"
[371] "X761"         "X762"         "X763"         "X764"         "X765"
[376] "X766"         "X767"         "X768"         "X769"         "X770"
[381] "X771"         "X772"         "X773"         "X774"         "X775"
[386] "X776"         "X777"         "X778"         "X779"         "X780"
[391] "X781"         "X782"         "X783"         "X784"         "X785"
[396] "X786"         "X787"         "X788"         "X789"         "X790"
[401] "X791"         "X792"         "X793"         "X794"         "X795"
[406] "X796"         "X797"         "X798"         "X799"         "X800"
[411] "X801"         "X802"         "X803"         "X804"         "X805"
[416] "X806"         "X807"         "X808"         "X809"         "X810"
[421] "X811"         "X812"         "X813"         "X814"         "X815"
[426] "X816"         "X817"         "X818"         "X819"         "X820"
[431] "X821"         "X822"         "X823"         "X824"         "X825"
[436] "X826"         "X827"         "X828"         "X829"         "X830"
[441] "X831"         "X832"         "X833"         "X834"         "X835"
[446] "X836"         "X837"         "X838"         "X839"         "X840"
[451] "X841"         "X842"         "X843"         "X844"         "X845"
[456] "X846"         "X847"         "X848"         "X849"         "X850"
[461] "X851"         "X852"         "X853"         "X854"         "X855"
[466] "X856"         "X857"         "X858"         "X859"         "X860"
[471] "X861"         "X862"         "X863"         "X864"         "X865"
[476] "X866"         "X867"         "X868"         "X869"         "X870"
[481] "X871"         "X872"         "X873"         "X874"         "X875"
[486] "X876"         "X877"         "X878"         "X879"         "X880"
[491] "X881"         "X882"         "X883"         "X884"         "X885"
[496] "X886"         "X887"         "X888"         "X889"         "X890"
[501] "X891"         "X892"         "X893"         "X894"         "X895"
[506] "X896"         "X897"         "X898"         "X899"         "X900"
[511] "X901"         "X902"         "X903"         "X904"         "X905"
[516] "X906"         "X907"         "X908"         "X909"         "X910"
[521] "X911"         "X912"         "X913"         "X914"         "X915"
[526] "X916"         "X917"         "X918"         "X919"         "X920"
[531] "X921"         "X922"         "X923"         "X924"         "X925"
[536] "X926"         "X927"         "X928"         "X929"         "X930"
[541] "X931"         "X932"         "X933"         "X934"         "X935"
[546] "X936"         "X937"         "X938"         "X939"         "X940"
[551] "X941"         "X942"         "X943"         "X944"         "X945"
[556] "X946"         "X947"         "X948"         "X949"         "X950"
[561] "X951"         "X952"         "X953"         "X954"         "X955"
[566] "X956"         "X957"         "X958"         "X959"         "X960"
[571] "X961"         "X962"         "X963"         "X964"         "X965"
[576] "X966"         "X967"         "X968"         "X969"         "X970"
[581] "X971"         "X972"         "X973"         "X974"         "X975"
[586] "X976"         "X977"         "X978"         "X979"         "X980"
[591] "X981"         "X982"         "X983"         "X984"         "X985"
[596] "X986"         "X987"         "X988"         "X989"         "X990"
[601] "X991"         "X992"         "X993"         "X994"         "X995"
[606] "X996"         "X997"         "X998"         "X999"         "X402.593_5nm"
[611] "X407.593_5nm" "X412.593_5nm" "X417.593_5nm" "X422.593_5nm" "X427.593_5nm"
[616] "X432.593_5nm" "X437.593_5nm" "X442.593_5nm" "X447.593_5nm" "X452.593_5nm"
[621] "X457.593_5nm" "X462.593_5nm" "X467.593_5nm" "X472.593_5nm" "X477.593_5nm"
[626] "X482.593_5nm" "X487.593_5nm" "X492.593_5nm" "X497.593_5nm" "X502.593_5nm"
[631] "X507.593_5nm" "X512.593_5nm" "X517.593_5nm" "X522.593_5nm" "X527.593_5nm"
[636] "X532.593_5nm" "X537.593_5nm" "X542.593_5nm" "X547.593_5nm" "X552.593_5nm"
[641] "X557.593_5nm" "X562.593_5nm" "X567.593_5nm" "X572.593_5nm" "X577.593_5nm"
[646] "X582.593_5nm" "X587.593_5nm" "X592.593_5nm" "X597.593_5nm" "X602.593_5nm"
[651] "X607.593_5nm" "X612.593_5nm" "X617.593_5nm" "X622.593_5nm" "X627.593_5nm"
[656] "X632.593_5nm" "X637.593_5nm" "X642.593_5nm" "X647.593_5nm" "X652.593_5nm"
[661] "X657.593_5nm" "X662.593_5nm" "X667.593_5nm" "X672.593_5nm" "X677.593_5nm"
[666] "X682.593_5nm" "X687.593_5nm" "X692.593_5nm" "X697.593_5nm" "X702.593_5nm"
[671] "X707.593_5nm" "X712.593_5nm" "X717.593_5nm" "X722.593_5nm" "X727.593_5nm"
[676] "X732.593_5nm" "X737.593_5nm" "X742.593_5nm" "X747.593_5nm" "X752.593_5nm"
[681] "X757.593_5nm" "X762.593_5nm" "X767.593_5nm" "X772.593_5nm" "X777.593_5nm"
[686] "X782.593_5nm" "X787.593_5nm" "X792.593_5nm" "X797.593_5nm" "X802.593_5nm"
[691] "X807.593_5nm" "X812.593_5nm" "X817.593_5nm" "X822.593_5nm" "X827.593_5nm"
[696] "X832.593_5nm" "X837.593_5nm" "X842.593_5nm" "X847.593_5nm" "X852.593_5nm"
[701] "X857.593_5nm" "X862.593_5nm" "X867.593_5nm" "X872.593_5nm" "X877.593_5nm"
[706] "X882.593_5nm" "X887.593_5nm" "X892.593_5nm" "X897.593_5nm" "X902.593_5nm"
[711] "X907.593_5nm" "X912.593_5nm" "X917.593_5nm" "X922.593_5nm" "X927.593_5nm"
[716] "X932.593_5nm" "X937.593_5nm" "X942.593_5nm" "X947.593_5nm" "X952.593_5nm"
[721] "X957.593_5nm" "X962.593_5nm" "X967.593_5nm" "X972.593_5nm" "X977.593_5nm"
[726] "X982.593_5nm" "X987.593_5nm" "X992.593_5nm" "Boochs"       "Boochs2"
[731] "CARI"         "Carter"       "Carter2"      "Carter3"      "Carter4"
[736] "Carter5"      "Carter6"      "CI"           "CI2"          "ClAInt"
[741] "CRI1"         "CRI2"         "CRI3"         "CRI4"         "D1"
[746] "D2"           "Datt"         "Datt2"        "Datt3"        "Datt4"
[751] "Datt5"        "Datt6"        "DD"           "DDn"          "DPI"
[756] "DWSI4"        "EGFN"         "EGFR"         "EVI"          "GDVI2"
[761] "GDVI3"        "GDVI4"        "GI"           "Gitelson"     "Gitelson2"
[766] "GMI1"         "GMI2"         "GreenNDVI"    "Maccioni"     "MCARI"
[771] "MCARIOSAVI"   "MCARI2"       "MCARI2OSAVI2" "mND705"       "mNDVI"
[776] "MPRI"         "MSAVI"        "mSR"          "mSR2"         "mSR705"
[781] "MTCI"         "MTVI"         "NDVI"         "NDVI2"        "NDVI3"
[786] "NPCI"         "OSAVI"        "OSAVI2"       "PARS"         "PRI"
[791] "PRICI2"       "PRInorm"      "PSND"         "PSRI"         "PSSR"
[796] "RDVI"         "REPLE"        "REPLi"        "SAVI"         "SIPI"
[801] "SPVI"         "SR"           "SR1"          "SR2"          "SR3"
[806] "SR4"          "SR5"          "SR6"          "SR7"          "SR8"
[811] "SRPI"         "SumDr1"       "SumDr2"       "TCARI"        "TCARIOSAVI"
[816] "TCARI2"       "TCARI2OSAVI2" "TGI"          "TVI"          "Vogelmann"
[821] "Vogelmann2"   "Vogelmann3"   "Vogelmann4"

In [28]:
num_per_pft <- 300
train_test_data <- create_patch_balanced_sample(
    df,
    test_count = 20,
    train_count = NULL,
    verbose = FALSE
    )

split_2_train <- create_patch_balanced_sample(
    train_test_data$remainder,
    test_count = num_per_pft,
    train_count = 1000,
    verbose = FALSE
    )

In [29]:
exclude_vars <- c('X', "UID", "ScanNum", "sample_name", "PFT", "FncGrp1", "Site")

target_variable <- "FncGrp1"

In [36]:
calculate_model_metrics <- function(
    model, 
    test_data, 
    test_labels, 
    seed,
    n = 4,
    model_dir = "./",
    manifest_path = "./seed_and_size.csv") {
    # create predictions (ranger)

        model_id <- uuid::UUIDgenerate()

        model_dir_full <- paste0(
                model_dir,
                model_id,
                "/"
            )

        if(!dir.exists(model_dir)){
            dir.create(model_dir)
        }

        dir.create(
            model_dir_full
        )


        model_predictions <- predict(
            model,
            test_data
        )$prediction %>% as.factor()

        confusion_matrix <- caret::confusionMatrix(
            model_predictions %>% to_fg0(),
            test_labels %>% as.factor() %>% to_fg0() %>% add_forb(),
            mode = "everything"
        )

        acc <- as.list(confusion_matrix$overall)$Accuracy
        print(paste0("Model Accuracy: ", acc))

        validate_model(
            model,
            save_directory = model_dir_full
        )

        aggregated_results <- aggregate_results(model_dir_full)
        r2 <- calculate_validation_r2(aggregated_results)
        rpd <- calculate_rpd(aggregated_results)

        print(r2)

        save(model, file = paste0(model_dir_full, "model.rda"))

        print(model_dir)
        plt <- plot_by_pft(
            aggregated_results,
            save_path = paste0(model_dir_full, "aggregate.html"),
            open = FALSE,
            image_path = NULL,
            aggregation = 0
        )
        
        add_model_to_manifest(
            model_id = model_id,
            model_type = "Random Forest",
            bandwidth = 5,
            max_count = 300,
            preprocessing = paste0(
                "none"
            ),
            max_correlation = "none",
            weight = "balanced",
            hyperparam1 = n,
            # oob_error = model$prediction.error,
            accuracy = acc,
            r2 = r2,
            rpd = rpd,
            seed = seed,
            logpath = manifest_path
        )
}

In [37]:
for(seed in seeds){
    set.seed(seed)

    # split the data based on the seed
    num_per_pft <- 300
    train_test_data <- create_patch_balanced_sample(
        df,
        test_count = 20,
        train_count = NULL,
        verbose = FALSE
        )

    split_2_train <- create_patch_balanced_sample(
        train_test_data$remainder,
        test_count = num_per_pft,
        train_count = 1000,
        verbose = FALSE
        )
    labels <- split_2_train$selection[,target_variable] %>% as.factor()
    test_labels <- train_test_data$selection[,target_variable] %>% as.factor()
    
    include_vars <- setdiff(
        colnames(split_2_train$selection),
        colnames(data_raw)
        )

    train_data <- impute_spectra(
        #clip_outliers(
            subset(
                x = split_2_train$selection,
                select = include_vars
                )
            )
        #)
    test_data <- impute_spectra(
        #clip_outliers(
            subset(
                train_test_data$selection,
                select = include_vars
                )
            )
        #)
    #if (("Forb" %in% levels(labels)) && !("Forb" %in% levels(test_labels))) {
    #    levels(test_labels) <- c(levels(test_labels), "Forb")
    #}
        
    small_model <- ranger::ranger(
        num.trees = 4,
        replace = TRUE,
        classification = TRUE,
        # alpha = a,
        case.weights = targets_to_weights(labels),
        x = train_data,
        y = labels
    )

    # reset seed
    set.seed(seed)
    big_model <- ranger::ranger(
        num.trees = 1000,
        replace = TRUE,
        classification = TRUE,
        # alpha = a,
        case.weights = targets_to_weights(labels),
        x = impute_spectra(train_data),
        y = labels
    )

    # and again for better reproducability
    set.seed(seed)
    calculate_model_metrics(
        small_model,
        train_test_data$selection[, include_vars],
        train_test_data$selection[, target_variable] %>% as.factor(),
        seed,
        n = 4,
        model_dir = "./temp/"
    )

    calculate_model_metrics(
        big_model,
        train_test_data$selection[, include_vars],
        train_test_data$selection[, target_variable] %>% as.factor(),
        seed,
        n = 1000,
        model_dir = "./temp/"
    )

    print(paste0("Iteration completed for seed ", seed))
}

Warning message in levels(reference) != levels(data):
“longer object length is not a multiple of shorter object length”
Warning message in confusionMatrix.default(model_predictions %>% to_fg0(), test_labels %>% :
“Levels are not in the same order for reference and data. Refactoring data to match.”

[1] "Model Accuracy: 0.8125"
[1] "preprocessing raster at Data/Ground_Validation/Imagery/BisonGulchQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `Bisoon_Quadrats_georeferenced' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/Bisoon_Quadrats_georeferenced.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 9 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -148.9524 ymin: 63.80698 xmax: -148.9508 ymax: 63.80701
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

[1] "preprocessing raster at Data/Ground_Validation/Imagery/ChatanikaQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `ChatanikaQuads_georeferenced_0_90m' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/ChatanikaQuads_georeferenced_0_90m.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 10 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -147.4825 ymin: 65.15281 xmax: -147.4806 ymax: 65.15286
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

[1] "preprocessing raster at Data/Ground_Validation/Imagery/EightMileQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `EightMile_Quadrats_revised' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/EightMile_Quadrats_revised.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 11 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -149.2549 ymin: 63.87666 xmax: -149.2529 ymax: 63.87686
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

[1] "preprocessing raster at Data/Ground_Validation/Imagery/BonanzaQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `Bonanza_N_Quads' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/Bonanza_N_Quads.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 11 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 438153.7 ymin: 7176051 xmax: 438205.6 ymax: 7176138
Projected CRS: WGS 84 / UTM zone 6N

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

  [1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [13]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [25]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [37]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [49]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [61]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [73]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [85]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [97]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[109]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[121]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[133]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[145]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[157]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[169]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[181]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[193]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[205]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[217]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[229]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[241]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[253]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[265]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[277]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[289]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[301]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[313]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[325]  TRUE  TRUE  TRUE FALSE
[1] 0.408077
[1] "./temp/"

Warning message in levels(reference) != levels(data):
“longer object length is not a multiple of shorter object length”
Warning message in confusionMatrix.default(model_predictions %>% to_fg0(), test_labels %>% :
“Levels are not in the same order for reference and data. Refactoring data to match.”

[1] "Model Accuracy: 0.88125"
[1] "preprocessing raster at Data/Ground_Validation/Imagery/BisonGulchQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `Bisoon_Quadrats_georeferenced' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/Bisoon_Quadrats_georeferenced.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 9 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -148.9524 ymin: 63.80698 xmax: -148.9508 ymax: 63.80701
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

[1] "preprocessing raster at Data/Ground_Validation/Imagery/ChatanikaQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `ChatanikaQuads_georeferenced_0_90m' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/ChatanikaQuads_georeferenced_0_90m.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 10 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -147.4825 ymin: 65.15281 xmax: -147.4806 ymax: 65.15286
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

[1] "preprocessing raster at Data/Ground_Validation/Imagery/EightMileQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `EightMile_Quadrats_revised' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/EightMile_Quadrats_revised.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 11 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -149.2549 ymin: 63.87666 xmax: -149.2529 ymax: 63.87686
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

[1] "preprocessing raster at Data/Ground_Validation/Imagery/BonanzaQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `Bonanza_N_Quads' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/Bonanza_N_Quads.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 11 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 438153.7 ymin: 7176051 xmax: 438205.6 ymax: 7176138
Projected CRS: WGS 84 / UTM zone 6N

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

  [1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [13]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [25]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [37]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [49]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [61]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [73]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [85]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [97]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[109]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[121]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[133]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[145]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[157]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[169]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[181]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[193]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[205]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[217]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[229]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[241]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[253]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[265]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[277]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[289]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[301]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[313]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[325]  TRUE  TRUE  TRUE FALSE
[1] 0.3872184
[1] "./temp/"
[1] "Iteration completed for seed 1378"

Warning message in levels(reference) != levels(data):
“longer object length is not a multiple of shorter object length”
Warning message in confusionMatrix.default(model_predictions %>% to_fg0(), test_labels %>% :
“Levels are not in the same order for reference and data. Refactoring data to match.”

[1] "Model Accuracy: 0.825"
[1] "preprocessing raster at Data/Ground_Validation/Imagery/BisonGulchQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `Bisoon_Quadrats_georeferenced' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/Bisoon_Quadrats_georeferenced.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 9 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -148.9524 ymin: 63.80698 xmax: -148.9508 ymax: 63.80701
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

[1] "preprocessing raster at Data/Ground_Validation/Imagery/ChatanikaQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `ChatanikaQuads_georeferenced_0_90m' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/ChatanikaQuads_georeferenced_0_90m.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 10 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -147.4825 ymin: 65.15281 xmax: -147.4806 ymax: 65.15286
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

[1] "preprocessing raster at Data/Ground_Validation/Imagery/EightMileQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `EightMile_Quadrats_revised' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/EightMile_Quadrats_revised.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 11 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -149.2549 ymin: 63.87666 xmax: -149.2529 ymax: 63.87686
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

[1] "preprocessing raster at Data/Ground_Validation/Imagery/BonanzaQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `Bonanza_N_Quads' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/Bonanza_N_Quads.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 11 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 438153.7 ymin: 7176051 xmax: 438205.6 ymax: 7176138
Projected CRS: WGS 84 / UTM zone 6N

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

  [1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [13]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [25]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [37]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [49]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [61]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [73]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [85]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [97]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[109]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[121]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[133]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[145]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[157]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[169]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[181]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[193]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[205]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[217]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[229]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[241]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[253]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[265]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[277]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[289]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[301]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[313]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[325]  TRUE  TRUE  TRUE FALSE
[1] 0.3307054
[1] "./temp/"

Warning message in levels(reference) != levels(data):
“longer object length is not a multiple of shorter object length”
Warning message in confusionMatrix.default(model_predictions %>% to_fg0(), test_labels %>% :
“Levels are not in the same order for reference and data. Refactoring data to match.”

[1] "Model Accuracy: 0.88125"
[1] "preprocessing raster at Data/Ground_Validation/Imagery/BisonGulchQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `Bisoon_Quadrats_georeferenced' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/Bisoon_Quadrats_georeferenced.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 9 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -148.9524 ymin: 63.80698 xmax: -148.9508 ymax: 63.80701
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

[1] "preprocessing raster at Data/Ground_Validation/Imagery/ChatanikaQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `ChatanikaQuads_georeferenced_0_90m' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/ChatanikaQuads_georeferenced_0_90m.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 10 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -147.4825 ymin: 65.15281 xmax: -147.4806 ymax: 65.15286
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

[1] "preprocessing raster at Data/Ground_Validation/Imagery/EightMileQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `EightMile_Quadrats_revised' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/EightMile_Quadrats_revised.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 11 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -149.2549 ymin: 63.87666 xmax: -149.2529 ymax: 63.87686
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

[1] "preprocessing raster at Data/Ground_Validation/Imagery/BonanzaQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `Bonanza_N_Quads' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/Bonanza_N_Quads.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 11 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 438153.7 ymin: 7176051 xmax: 438205.6 ymax: 7176138
Projected CRS: WGS 84 / UTM zone 6N

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

  [1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [13]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [25]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [37]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [49]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [61]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [73]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [85]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [97]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[109]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[121]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[133]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[145]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[157]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[169]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[181]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[193]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[205]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[217]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[229]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[241]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[253]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[265]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[277]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[289]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[301]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[313]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[325]  TRUE  TRUE  TRUE FALSE
[1] 0.3511848
[1] "./temp/"
[1] "Iteration completed for seed 3964"

Warning message in levels(reference) != levels(data):
“longer object length is not a multiple of shorter object length”
Warning message in confusionMatrix.default(model_predictions %>% to_fg0(), test_labels %>% :
“Levels are not in the same order for reference and data. Refactoring data to match.”

[1] "Model Accuracy: 0.75"
[1] "preprocessing raster at Data/Ground_Validation/Imagery/BisonGulchQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `Bisoon_Quadrats_georeferenced' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/Bisoon_Quadrats_georeferenced.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 9 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -148.9524 ymin: 63.80698 xmax: -148.9508 ymax: 63.80701
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

[1] "preprocessing raster at Data/Ground_Validation/Imagery/ChatanikaQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `ChatanikaQuads_georeferenced_0_90m' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/ChatanikaQuads_georeferenced_0_90m.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 10 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -147.4825 ymin: 65.15281 xmax: -147.4806 ymax: 65.15286
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

[1] "preprocessing raster at Data/Ground_Validation/Imagery/EightMileQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `EightMile_Quadrats_revised' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/EightMile_Quadrats_revised.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 11 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -149.2549 ymin: 63.87666 xmax: -149.2529 ymax: 63.87686
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

[1] "preprocessing raster at Data/Ground_Validation/Imagery/BonanzaQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `Bonanza_N_Quads' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/Bonanza_N_Quads.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 11 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 438153.7 ymin: 7176051 xmax: 438205.6 ymax: 7176138
Projected CRS: WGS 84 / UTM zone 6N

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

  [1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [13]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [25]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [37]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [49]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [61]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [73]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [85]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [97]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[109]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[121]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[133]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[145]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[157]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[169]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[181]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[193]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[205]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[217]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[229]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[241]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[253]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[265]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[277]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[289]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[301]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[313]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[325]  TRUE  TRUE  TRUE FALSE
[1] 0.3756808
[1] "./temp/"

Warning message in levels(reference) != levels(data):
“longer object length is not a multiple of shorter object length”
Warning message in confusionMatrix.default(model_predictions %>% to_fg0(), test_labels %>% :
“Levels are not in the same order for reference and data. Refactoring data to match.”

[1] "Model Accuracy: 0.8625"
[1] "preprocessing raster at Data/Ground_Validation/Imagery/BisonGulchQuads.envi"
[1] "Converted to Data frame?"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716" "X997.568" "X999.42"
[1] "Noisy columns removed"
[1] TRUE
  [1] "x"        "y"        "X397.593" "X399.444" "X401.296" "X403.148"
  [7] "X405"     "X406.851" "X408.703" "X410.555" "X412.407" "X414.258"
 [13] "X416.11"  "X417.962" "X419.814" "X421.666" "X423.517" "X425.369"
 [19] "X427.221" "X429.073" "X430.924" "X432.776" "X434.628" "X436.48"
 [25] "X438.332" "X440.183" "X442.035" "X443.887" "X445.739" "X447.59"
 [31] "X449.442" "X451.294" "X453.146" "X454.998" "X456.849" "X458.701"
 [37] "X460.553" "X462.405" "X464.256" "X466.108" "X467.96"  "X469.812"
 [43] "X471.664" "X473.515" "X475.367" "X477.219" "X479.071" "X480.922"
 [49] "X482.774" "X484.626" "X486.478" "X488.33"  "X490.181" "X492.033"
 [55] "X493.885" "X495.737" "X497.588" "X499.44"  "X501.292" "X503.144"
 [61] "X504.996" "X506.847" "X508.699" "X510.551" "X512.403" "X514.254"
 [67] "X516.106" "X517.958" "X519.81"  "X521.662" "X523.513" "X525.365"
 [73] "X527.217" "X529.069" "X530.92"  "X532.772" "X534.624" "X536.476"
 [79] "X538.328" "X540.179" "X542.031" "X543.883" "X545.735" "X547.586"
 [85] "X549.438" "X551.29"  "X553.142" "X554.994" "X556.845" "X558.697"
 [91] "X560.549" "X562.401" "X564.252" "X566.104" "X567.956" "X569.808"
 [97] "X571.659" "X573.511" "X575.363" "X577.215" "X579.067" "X580.918"
[103] "X582.77"  "X584.622" "X586.474" "X588.325" "X590.177" "X592.029"
[109] "X593.881" "X595.733" "X597.584" "X599.436" "X601.288" "X603.14"
[115] "X604.991" "X606.843" "X608.695" "X610.547" "X612.399" "X614.25"
[121] "X616.102" "X617.954" "X619.806" "X621.657" "X623.509" "X625.361"
[127] "X627.213" "X629.065" "X630.916" "X632.768" "X634.62"  "X636.472"
[133] "X638.323" "X640.175" "X642.027" "X643.879" "X645.731" "X647.582"
[139] "X649.434" "X651.286" "X653.138" "X654.989" "X656.841" "X658.693"
[145] "X660.545" "X662.397" "X664.248" "X666.1"   "X667.952" "X669.804"
[151] "X671.655" "X673.507" "X675.359" "X677.211" "X679.063" "X680.914"
[157] "X682.766" "X684.618" "X686.47"  "X688.321" "X690.173" "X692.025"
[163] "X693.877" "X695.729" "X697.58"  "X699.432" "X701.284" "X703.136"
[169] "X704.987" "X706.839" "X708.691" "X710.543" "X712.395" "X714.246"
[175] "X716.098" "X717.95"  "X719.802" "X721.653" "X723.505" "X725.357"
[181] "X727.209" "X729.061" "X730.912" "X732.764" "X734.616" "X736.468"
[187] "X738.319" "X740.171" "X742.023" "X743.875" "X745.726" "X747.578"
[193] "X749.43"  "X751.282" "X753.134" "X754.985" "X756.837" "X758.689"
[199] "X760.541" "X762.392" "X764.244" "X766.096" "X767.948" "X769.8"
[205] "X771.651" "X773.503" "X775.355" "X777.207" "X779.058" "X780.91"
[211] "X782.762" "X784.614" "X786.466" "X788.317" "X790.169" "X792.021"
[217] "X793.873" "X795.724" "X797.576" "X799.428" "X801.28"  "X803.132"
[223] "X804.983" "X806.835" "X808.687" "X810.539" "X812.39"  "X814.242"
[229] "X816.094" "X817.946" "X819.798" "X821.649" "X823.501" "X825.353"
[235] "X827.205" "X829.056" "X830.908" "X832.76"  "X834.612" "X836.464"
[241] "X838.315" "X840.167" "X842.019" "X843.871" "X845.722" "X847.574"
[247] "X849.426" "X851.278" "X853.13"  "X854.981" "X856.833" "X858.685"
[253] "X860.537" "X862.388" "X864.24"  "X866.092" "X867.944" "X869.796"
[259] "X871.647" "X873.499" "X875.351" "X877.203" "X879.054" "X880.906"
[265] "X882.758" "X884.61"  "X886.462" "X888.313" "X890.165" "X892.017"
[271] "X893.869" "X895.72"  "X897.572" "X899.424" "X901.276" "X903.127"
[277] "X904.979" "X906.831" "X908.683" "X910.535" "X912.386" "X914.238"
[283] "X916.09"  "X917.942" "X919.793" "X921.645" "X923.497" "X925.349"
[289] "X927.201" "X929.052" "X930.904" "X932.756" "X934.608" "X936.459"
[295] "X938.311" "X940.163" "X942.015" "X943.867" "X945.718" "X947.57"
[301] "X949.422" "X951.274" "X953.125" "X954.977" "X956.829" "X958.681"
[307] "X960.533" "X962.384" "X964.236" "X966.088" "X967.94"  "X969.791"
[313] "X971.643" "X973.495" "X975.347" "X977.199" "X979.05"  "X980.902"
[319] "X982.754" "X984.606" "X986.457" "X988.309" "X990.161" "X992.013"
[325] "X993.865" "X995.716"
[1] "Filtered"
[1] TRUE

Using spline to predict value at new bands...

Beware the spectra are now partially smoothed.

[1] "data.frame"

`.cols` has been renamed and is deprecated, please use `.vars`

[1] "Handling Outliers with method: none"
[1] "Transforming the data with transform: none"

`.cols` has been renamed and is deprecated, please use `.vars`

Reading layer `Bisoon_Quadrats_georeferenced' from data source
  `/home/krbundy/GitHub/lecospec/Data/Vectors/Bisoon_Quadrats_georeferenced.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 9 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -148.9524 ymin: 63.80698 xmax: -148.9508 ymax: 63.80701
Geodetic CRS:  WGS 84

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image

In [39]:
results <- read.csv("./seed_and_size.csv")

head(results)

  maxCount bandwidth maxCorrelation preprocessing weight   hyperparam1
1 300      5         none           none          balanced    4
2 300      5         none           none          balanced 1000
3 300      5         none           none          balanced    4
4 300      5         none           none          balanced 1000
5 300      5         none           none          balanced    4
6 300      5         none           none          balanced 1000
  hyperparam2 accuracy r2        rpd      seed
1 NA          0.83125  0.3603392 1.051130 6265
2 NA          0.86250  0.3342386 1.350129 6265
3 NA          0.81250  0.3211105 1.073748 4041
4 NA          0.90625  0.3128352 1.333134 4041
5 NA          0.81875  0.4142811 1.166157 3621
6 NA          0.87500  0.3748756 1.329950 3621
  model_id
1 179e38c2-416f-489a-86b2-2f1eb7c47425
2 916eaee3-1c9c-4ae9-b152-890461b8e44a
3 b50f6b23-ad71-4231-aa51-e39e9363e9b5
4 32812298-6adb-4402-ab24-8c5106017dbe
5 eac3817e-e5f4-4b5d-9ba5-94efb8c6467d
6 665a10b2-7d29-46f4-8ea6-5cdbc21854b7

In [70]:
small_results <- results[results$hyperparam1 == 4,] %>% as.data.frame()
large_results <- results[results$hyperparam1 == 1000,] %>% as.data.frame()
head(small_results)

   maxCount bandwidth maxCorrelation preprocessing weight   hyperparam1
1  300      5         none           none          balanced 4
3  300      5         none           none          balanced 4
5  300      5         none           none          balanced 4
7  300      5         none           none          balanced 4
9  300      5         none           none          balanced 4
11 300      5         none           none          balanced 4
   hyperparam2 accuracy r2        rpd      seed
1  NA          0.83125  0.3603392 1.051130 6265
3  NA          0.81250  0.3211105 1.073748 4041
5  NA          0.81875  0.4142811 1.166157 3621
7  NA          0.79375  0.3389215 1.141278  942
9  NA          0.85625  0.4971012 1.036625 3143
11 NA          0.83125  0.3603392 1.051130 6265
   model_id
1  179e38c2-416f-489a-86b2-2f1eb7c47425
3  b50f6b23-ad71-4231-aa51-e39e9363e9b5
5  eac3817e-e5f4-4b5d-9ba5-94efb8c6467d
7  fe3d3725-6cad-4b9d-8dce-32cda9e9495a
9  a4e814d5-c425-4f7b-a719-56f2b293b048
11 04eccb5d-8048-4efb-97c7-c31cd35a73d1

In [71]:
print(small_results$accuracy)

 [1] 0.83125 0.81250 0.81875 0.79375 0.85625 0.83125 0.81250 0.81875 0.79375
[10] 0.85625 0.81250 0.82500 0.75000

In [72]:
is.atomic(small_results$accuracy)

[1] TRUE

In [80]:
s_acc_m <- mean(small_results$accuracy)
s_acc_v <- var(small_results$accuracy, y = small_results$accuracy, na.rm = TRUE)
s_r2_m <- mean(small_results$r2)
s_r2_v <- var(small_results$r2, y = small_results$r2, na.rm = TRUE)
s_rpd_m <- mean(small_results$rpd)
s_rpd_v <- var(small_results$rpd, y = small_results$rpd)

l_acc_v <- var(large_results$accuracy, y = large_results$accuracy)
l_acc_m <- mean(large_results$accuracy %>% as.numeric())
l_r2_m <- mean(large_results$r2 %>% as.numeric())
l_r2_v <- var(large_results$r2, y = large_results$r2)
l_rpd_m <- mean(large_results$rpd)
l_rpd_v <- var(large_results$rpd,y = large_results$rpd)

print(
        paste("           Accuracy           Variance           r-squared           Variance            RPD           Variance")
)
        print(paste("Large", l_acc_m, l_acc_v, l_r2_m, l_r2_v, l_rpd_m, l_rpd_v, sep = "  "))
        print(paste("Small", s_acc_m, s_acc_v, s_r2_m, s_r2_v, s_rpd_m, s_rpd_v, sep = "  "))

[1] "           Accuracy           Variance           r-squared           Variance            RPD           Variance"
[1] "Large  0.888541666666667  0.000474668560606061  0.335160543853509  0.000882065647873394  1.34507371180415  0.000768781047722141"
[1] "Small  0.816346153846154  0.000765224358974359  0.382920776472048  0.00366547695006319  1.09139334329209  0.00271546776010004"